export enum ActionKind {
  CREATED_REVIEW = 'CREATED_REVIEW',
  DELETED_REVIEW = 'DELETED_REVIEW',
  CREATED_LIKE = 'CREATED_LIKE',
  DELETED_LIKE = 'DELETED_LIKE',
  CREATED_COMMENT = 'CREATED_COMMENT',
  DELETED_COMMENT = 'DELETED_COMMENT',
}
