export enum ActionKind {
  CREATED_REVIEW = 'CREATED_REVIEW',
  DELETED_REVIEW = 'DELETED_REVIEW',
  CREATED_LIKE = 'CREATED_LIKE',
  RECEIVED_LIKE_IN_REVIEW = 'RECEIVED_LIKE_IN_REVIEW',
  DELETED_LIKE = 'DELETED_LIKE',
  DELETED_LIKE_IN_REVIEW = 'DELETED_LIKE_IN_REVIEW',
  CREATED_COMMENT = 'CREATED_COMMENT',
  RECEIVED_COMMENT_IN_REVIEW = 'RECEIVED_COMMENT_IN_REVIEW',
  DELETED_COMMENT = 'DELETED_COMMENT',
  DELETED_COMMENT_IN_REVIEW = 'DELETED_COMMENT_IN_REVIEW',
}
