apiVersion: apps/v1
kind: Deployment
metadata:
  name: rank-service
  labels:
    app: rank-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rank-service
  template:
    metadata:
      labels:
        app: rank-service
    spec:
      containers:
        - name: rank-service
          image: cauahrq/rank-service:v3
          ports:
            - containerPort: 3001
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '128Mi'
              cpu: '250m'
          env:
            - name: PORT
              value: '3002'
            - name: DATABASE_HOST
              value: 'localhost'
            - name: DATABASE_PORT
              value: '5432'
            - name: DATABASE_USERNAME
              value: 'postgres'
            - name: DATABASE_PASSWORD
              value: '123456'
            - name: DATABASE_NAME
              value: 'rank'
            - name: SERVICE_NAME
              value: 'rank-service'
            - name: KAFKA_BROKER_HOST
              value: 'localhost:9094'
            - name: NODE_ENV
              value: 'development'
      restartPolicy: Always
