export const CREATE_RANK_FACTORY = 'CREATE_RANK_FACTORY';
export const FIND_RANKS_FACTORY = 'FIND_RANKS_FACTORY';

export const CREATE_ACTION_FACTORY = 'CREATE_ACTION_FACTORY';
export const FIND_ACTIONS_FACTORY = 'FIND_ACTIONS_FACTORY';

export const PROCESS_USER_ACTION_FACTORY = 'PROCESS_USER_ACTION_FACTORY';
