export const RANK_REPOSITORY = 'RANK_REPOSITORY';
export const ACTION_REPOSITORY = 'ACTION_REPOSITORY';
export const USER_ACTION_REPOSITORY = 'USER_ACTION_REPOSITORY';
export const USER_RANK_REPOSITORY = 'USER_RANK_REPOSITORY';
